---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  interval: 1m0s
  ref:
    branch: {{ .Values.fluxGitRepositoryBranch }}
  secretRef:
    name: {{ .Values.fluxGitRepositorySecret }}
  url: {{ .Values.fluxGitRepository }}

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  interval: 10m0s
  path: {{ .Values.fluxGitRepositoryPath }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
